import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import SectionType from '@/src/components/section-type/section_type'
const inter = Inter({ subsets: ['latin'] })

export default function Home({ section_data, unique_section }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
      </Head>
      <main className={styles.main}>
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="/section/dynamic_grid">dynamic_grid</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/section/gap">gap</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/section/dynamic_slider_grid">dynamic_slider_grid</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/section/product_grid">product_grid</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <h1>{unique_section}</h1>
          <div class="row">
            {section_data.map((sec) => (

              <div class="col-lg-4">
                <Image height={300} width={300} src='https://picsum.photos/200/300' alt={sec.title} />
                <h5>{sec.title}</h5>
                <p>{sec.slug}</p>
                <p>{sec.brand}</p>
              </div>
            )
            )}
          </div>
        </div>

      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch("https://prodapp.lifepharmacy.com/api/cms/page/home");
  const data = await res.json();
  var section_type = [];
  for (var con of data.data.content) {
    section_type.push(con.section_type);
  }
  let uniqueChars = [...new Set(section_type)];
  for (var unique_section of uniqueChars) {
    // all dynamic grids filtered
    const filter_data = data.data.content.filter(d => d.section_type === unique_section);

    //iterating through each section_data_array of every content in dynamic_grid
    var section_data = []

    for (var con of filter_data) {
      for (var sec of con.section_data_array) {
        section_data.push(sec);
      }
    }

    // console.log(section_data[0].desktop.image_url);

    // console.log(data_content);

    // console.log(filter_data.map(e => e.section_data_array));
    return {
      props: {
        section_data,
        unique_section,
      }
    }
  }
}